### ISSUE TITLE
Naming Collision: messages.properties

### ISSUE THREAD

**Issue by odn2se** [danshannon/javastravav3api#108]
The Grails framework also uses the messages.properties file for internationalization (see http://grails.github.io/grails-doc/2.4.3/guide/i18n.html), so when the [Messages](https://github.com/danshannon/javastravav3api/blob/master/Strava%20API%20v3/src/javastrava/config/Messages.java) class attempts to load the "messages" bundle it is actually loading the Grails properties file. This causes problems with Retrofit error handling. Can I submit a pull request to change to a new, more unique, name? Or maybe there is a more elegant way to solve this issue...

Stacktrace:
```
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key RetrofitErrorHandler.unknownError
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450) ~[na:1.8.0_45]
        at java.util.ResourceBundle.getString(ResourceBundle.java:407) ~[na:1.8.0_45]
        at javastrava.config.Messages.string(Messages.java:27) ~[javastrava-api-1.0.0-RC2.jar:na]
        at javastrava.api.v3.rest.util.RetrofitErrorHandler.handleError(RetrofitErrorHandler.java:82) ~[javastrava-api-1.0.0-RC2.jar:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242) ~[retrofit-1.9.0.jar:na]
        at javastrava.api.v3.auth.impl.retrofit.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:39) ~[javastrava-api-1.0.0-RC2.jar:na]
```

**Comment by danshannon** [comment]
Hi PHIL

You're welcome to submit a pull request - I will get to it but it might take a week or so at the moment

Cheers

Dan

Sent from my iPhone

On 26 Jun 2015, at 3:41 pm, Phil Anderson <notifications@github.com> wrote:

The Grails framework also uses the messages.properties file for internationalization (see http://grails.github.io/grails-doc/2.4.3/guide/i18n.html), so when the Messages class attempts to load the "messages" bundle it is actually loading the Grails properties file. This causes problems with Retrofit error handling. Can I submit a pull request to change to a new, more unique, name? Or maybe there is a more elegant way to solve this issue...

Stacktrace:

Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key RetrofitErrorHandler.unknownError
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450) ~[na:1.8.0_45]
        at java.util.ResourceBundle.getString(ResourceBundle.java:407) ~[na:1.8.0_45]
        at javastrava.config.Messages.string(Messages.java:27) ~[javastrava-api-1.0.0-RC2.jar:na]
        at javastrava.api.v3.rest.util.RetrofitErrorHandler.handleError(RetrofitErrorHandler.java:82) ~[javastrava-api-1.0.0-RC2.jar:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242) ~[retrofit-1.9.0.jar:na]
        at javastrava.api.v3.auth.impl.retrofit.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:39) ~[javastrava-api-1.0.0-RC2.jar:na]

**Comment by odn2se** [comment]
Thanks, I've created the pull request https://github.com/danshannon/javastravav3api/pull/109

**Comment by danshannon** [comment]
Moved to java-strava-message.properties
