### ISSUE TITLE
ArrayIndexOutOfBoundsException while deploying on weblogic

### ISSUE THREAD

**Issue by yarayaseen** [danshannon/javastravav3api#110]
I get this exception 
java.lang.ArrayIndexOutOfBoundsException: 23684
while deploying my app on weblogic, I tried older versions but I had another problem with the java version, right now I am using java 7

**Comment by danshannon** [comment]
Can you post the full stack trace?

Sent from my iPhone

On 23 Oct 2015, at 7:58 AM, yarayaseen <notifications@github.com> wrote:

I get this exception 
java.lang.ArrayIndexOutOfBoundsException: 23684
while deploying my app on weblogic, I tried older versions but I had another problem with the java version, right now I am using java 7

**Comment by yarayaseen** [comment]
java.lang.ArrayIndexOutOfBoundsException: 23684
	at com.bea.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.bea.objectweb.asm.ClassReader.<init>(Unknown Source)
	at weblogic.application.utils.annotation.ClassInfoImpl.<init>(ClassInfoImpl.java:51)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.polulateOneClassInfo(ClassfinderClassInfos.java:170)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.populateClassInfos(ClassfinderClassInfos.java:162)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.<init>(ClassfinderClassInfos.java:35)
	at weblogic.servlet.internal.War.initializeClassInfosIfNecessary(War.java:443)
	at weblogic.servlet.internal.War.getAnnotatedClasses(War.java:373)
	at weblogic.servlet.internal.WebBaseModuleExtensionContext.getAnnotatedClasses(WebBaseModuleExtensionContext.java:63)
	at weblogic.ejb.container.deployer.BaseModuleExtensionFactory.hasAnnotatedEJBs(BaseModuleExtensionFactory.java:50)
	at weblogic.ejb.container.deployer.EjbModuleExtensionFactory.create(EjbModuleExtensionFactory.java:21)
	at weblogic.application.internal.ExtensibleModuleWrapper.createModuleExtensions(ExtensibleModuleWrapper.java:264)
	at weblogic.application.internal.ExtensibleModuleWrapper.initDrivenObjectArray(ExtensibleModuleWrapper.java:232)
	at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:107)
	at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:172)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:167)
	at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
	at weblogic.work.ContextWrap.run(ContextWrap.java:40)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:550)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:295)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:254)

**Comment by yarayaseen** [comment]
Which version can I use with java 7 ?

**Comment by danshannon** [comment]
Given that none of the stack trace has to do with javastrava, it's hard for me to judge but it looks like it's a weblogic issue

Sent from my iPhone

On 23 Oct 2015, at 8:04 PM, yarayaseen <notifications@github.com> wrote:

java.lang.ArrayIndexOutOfBoundsException: 23684
at com.bea.objectweb.asm.ClassReader.(Unknown Source)
at com.bea.objectweb.asm.ClassReader.(Unknown Source)
at weblogic.application.utils.annotation.ClassInfoImpl.(ClassInfoImpl.java:51)
at weblogic.application.utils.annotation.ClassfinderClassInfos.polulateOneClassInfo(ClassfinderClassInfos.java:170)
at weblogic.application.utils.annotation.ClassfinderClassInfos.populateClassInfos(ClassfinderClassInfos.java:162)
at weblogic.application.utils.annotation.ClassfinderClassInfos.(ClassfinderClassInfos.java:35)
at weblogic.servlet.internal.War.initializeClassInfosIfNecessary(War.java:443)
at weblogic.servlet.internal.War.getAnnotatedClasses(War.java:373)
at weblogic.servlet.internal.WebBaseModuleExtensionContext.getAnnotatedClasses(WebBaseModuleExtensionContext.java:63)
at weblogic.ejb.container.deployer.BaseModuleExtensionFactory.hasAnnotatedEJBs(BaseModuleExtensionFactory.java:50)
at weblogic.ejb.container.deployer.EjbModuleExtensionFactory.create(EjbModuleExtensionFactory.java:21)
at weblogic.application.internal.ExtensibleModuleWrapper.createModuleExtensions(ExtensibleModuleWrapper.java:264)
at weblogic.application.internal.ExtensibleModuleWrapper.initDrivenObjectArray(ExtensibleModuleWrapper.java:232)
at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:107)
at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:172)
at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:167)
at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
at weblogic.work.ContextWrap.run(ContextWrap.java:40)
at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:550)
at weblogic.work.ExecuteThread.execute(ExecuteThread.java:295)
at weblogic.work.ExecuteThread.run(ExecuteThread.java:254)

**Comment by yarayaseen** [comment]
Does this version 1.0.0-RC2 work with java 7 ?

**Comment by danshannon** [comment]
Ah – no it requires features in Java 8 (mostly the asynchronous handling is done with CompletableFuture which is a new feature in 8)

**Comment by danshannon** [comment]
@yarayaseen closing this - feel free to reopen if appropriate
