### ISSUE TITLE
jcs error when using the raw API

### ISSUE THREAD

**Issue by patoupatou** [danshannon/javastravav3api#116]
I get this when trying the simple use case for raw API in the readme.md : 

```
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheManager getInstance
INFO: Instance is null, creating with config [/cache.ccf]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheManager configure
INFO: Creating cache manager from config file: /cache.ccf
May 30, 2016 3:47:03 PM org.apache.commons.jcs.utils.threadpool.ThreadPoolManager loadConfig
INFO: thread_pool.default PoolConfiguration = useBoundary = [true] boundarySize = [2000] maximumPoolSize = [150] minimumPoolSize = [4] keepAliveTime = [300000] whenBlockedPolicy = [RUN] startUpSize = [4]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator setDefaultAuxValues
INFO: Setting default auxiliaries to 
May 30, 2016 3:47:03 PM org.apache.commons.jcs.utils.config.OptionConverter instantiateByClassName
SEVERE: Could not instaMay 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheManager getInstance
INFO: Instance is null, creating with config [/cache.ccf]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheManager configure
INFO: Creating cache manager from config file: /cache.ccf
May 30, 2016 3:47:03 PM org.apache.commons.jcs.utils.threadpool.ThreadPoolManager loadConfig
INFO: thread_pool.default PoolConfiguration = useBoundary = [true] boundarySize = [2000] maximumPoolSize = [150] minimumPoolSize = [4] keepAliveTime = [300000] whenBlockedPolicy = [RUN] startUpSize = [4]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator setDefaultAuxValues
INFO: Setting default auxiliaries to 
May 30, 2016 3:47:03 PM org.apache.commons.jcs.utils.config.OptionConverter instantiateByClassName
SEVERE: Could not instantiate class []
java.lang.ClassNotFoundException: 
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.apache.commons.jcs.utils.config.OptionConverter.instantiateByClassName(OptionConverter.java:321)
    at org.apache.commons.jcs.utils.config.OptionConverter.instantiateByKey(OptionConverter.java:175)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.parseCompositeCacheAttributes(CompositeCacheConfigurator.java:445)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.setDefaultCompositeCacheAttributes(CompositeCacheConfigurator.java:210)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.doConfigure(CompositeCacheConfigurator.java:167)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.doConfigure(CompositeCacheManager.java:482)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:431)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:381)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:363)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:352)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getInstance(CompositeCacheManager.java:180)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getInstance(CompositeCacheManager.java:151)
    at org.apache.commons.jcs.JCS.getCacheManager(JCS.java:147)
    at org.apache.commons.jcs.JCS.getGroupCacheInstance(JCS.java:194)
    at javastrava.cache.impl.StravaCacheImpl.<init>(StravaCacheImpl.java:40)
    at javastrava.api.v3.service.impl.ActivityServiceImpl.<init>(ActivityServiceImpl.java:93)
    at javastrava.api.v3.service.impl.ActivityServiceImpl.instance(ActivityServiceImpl.java:58)
    at javastrava.api.v3.auth.model.Token.<init>(Token.java:114)
    at Main.main(Main.java:33)

May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseCompositeCacheAttributes
INFO: No special CompositeCacheAttributes class defined for key [jcs.default.cacheattributes], using default class.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator setDefaultCompositeCacheAttributes
INFO: setting defaultCompositeCacheAttributes to [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 1000, maxSpoolPerRun = -1, diskUsagePattern = SWAP, spoolChunkSize = 2 ]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseElementAttributes
INFO: No special ElementAttribute class defined for key [jcs.default.elementattributes], using default class.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator setDefaultElementAttributes
INFO: setting defaultElementAttributes to [ IS_LATERAL = true, IS_SPOOL = true, IS_REMOTE = true, IS_ETERNAL = true, MaxLifeSeconds = -1, IdleTime = -1, CreateTime = 1464637623140, LastAccessTime = 1464637623140, getTimeToLiveSeconds() = -1, createTime = 1464637623140 ]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseRegions
INFO: Parsed regions []
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator doConfigure
INFO: Finished configuration in 11 ms.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseElementAttributes
INFO: No special ElementAttribute class defined for key [jcs.region.default.elementattributes], using default class.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCache createMemoryCache
WARNING: Failed to init mem cache, using: LRUMemoryCache
java.lang.ClassNotFoundException: 
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.apache.commons.jcs.engine.control.CompositeCache.createMemoryCache(CompositeCache.java:1715)
    at org.apache.commons.jcs.engine.control.CompositeCache.<init>(CompositeCache.java:131)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.parseRegion(CompositeCacheConfigurator.java:340)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.parseRegion(CompositeCacheConfigurator.java:319)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getCache(CompositeCacheManager.java:609)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getCache(CompositeCacheManager.java:549)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getCache(CompositeCacheManager.java:536)
    at org.apache.commons.jcs.JCS.getGroupCacheInstance(JCS.java:194)
    at javastrava.cache.impl.StravaCacheImpl.<init>(StravaCacheImpl.java:40)
    at javastrava.api.v3.service.impl.ActivityServiceImpl.<init>(ActivityServiceImpl.java:93)
    at javastrava.api.v3.service.impl.ActivityServiceImpl.instance(ActivityServiceImpl.java:58)
    at javastrava.api.v3.auth.model.Token.<init>(Token.java:114)
    at Main.main(Main.java:33)

May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.memory.AbstractDoubleLinkedListMemoryCache initialize
INFO: initialized MemoryCache for default
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCache <init>
INFO: Constructed cache with name [default] and cache attributes [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 1000, maxSpoolPerRun = -1, diskUsagePattern = SWAP, spoolChunkSize = 2 ]
Exception in thread "main" java.lang.ExceptionInInitializerError
    at javastrava.api.v3.auth.model.Token.<init>(Token.java:123)
    at Main.main(Main.java:33)
Caused by: java.util.MissingResourceException: Can't find bundle for base name application, locale en_US
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
    at javastrava.api.v3.service.impl.WebhookServiceImpl.<clinit>(WebhookServiceImpl.java:28)
    ... 2 more
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheManager run
INFO: Shutdown hook activated.  Shutdown was not called.  Shutting down JCS.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.event.ElementEventQueue dispose
INFO: Element event queue destroyed: org.apache.commons.jcs.engine.control.event.ElementEventQueue@7c8c5901
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
INFO: In DISPOSE, [default] fromRemote [false]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
INFO: In DISPOSE, [default] disposing of memory cache.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.memory.AbstractMemoryCache dispose
INFO: Memory Cache dispose called.
ntiate class []
java.lang.ClassNotFoundException: 
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.apache.commons.jcs.utils.config.OptionConverter.instantiateByClassName(OptionConverter.java:321)
    at org.apache.commons.jcs.utils.config.OptionConverter.instantiateByKey(OptionConverter.java:175)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.parseCompositeCacheAttributes(CompositeCacheConfigurator.java:445)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.setDefaultCompositeCacheAttributes(CompositeCacheConfigurator.java:210)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.doConfigure(CompositeCacheConfigurator.java:167)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.doConfigure(CompositeCacheManager.java:482)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:431)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:381)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:363)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:352)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getInstance(CompositeCacheManager.java:180)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getInstance(CompositeCacheManager.java:151)
    at org.apache.commons.jcs.JCS.getCacheManager(JCS.java:147)
    at org.apache.commons.jcs.JCS.getGroupCacheInstance(JCS.java:194)
    at javastrava.cache.impl.StravaCacheImpl.<init>(StravaCacheImpl.java:40)
    at javastrava.api.v3.service.impl.ActivityServiceImpl.<init>(ActivityServiceImpl.java:93)
    at javastrava.api.v3.service.impl.ActivityServiceImpl.instance(ActivityServiceImpl.java:58)
    at javastrava.api.v3.auth.model.Token.<init>(Token.java:114)
    at Main.main(Main.java:33)

May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseCompositeCacheAttributes
INFO: No special CompositeCacheAttributes class defined for key [jcs.default.cacheattributes], using default class.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator setDefaultCompositeCacheAttributes
INFO: setting defaultCompositeCacheAttributes to [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 1000, maxSpoolPerRun = -1, diskUsagePattern = SWAP, spoolChunkSize = 2 ]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseElementAttributes
INFO: No special ElementAttribute class defined for key [jcs.default.elementattributes], using default class.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator setDefaultElementAttributes
INFO: setting defaultElementAttributes to [ IS_LATERAL = true, IS_SPOOL = true, IS_REMOTE = true, IS_ETERNAL = true, MaxLifeSeconds = -1, IdleTime = -1, CreateTime = 1464637623140, LastAccessTime = 1464637623140, getTimeToLiveSeconds() = -1, createTime = 1464637623140 ]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseRegions
INFO: Parsed regions []
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator doConfigure
INFO: Finished configuration in 11 ms.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheConfigurator parseElementAttributes
INFO: No special ElementAttribute class defined for key [jcs.region.default.elementattributes], using default class.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCache createMemoryCache
WARNING: Failed to init mem cache, using: LRUMemoryCache
java.lang.ClassNotFoundException: 
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.apache.commons.jcs.engine.control.CompositeCache.createMemoryCache(CompositeCache.java:1715)
    at org.apache.commons.jcs.engine.control.CompositeCache.<init>(CompositeCache.java:131)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.parseRegion(CompositeCacheConfigurator.java:340)
    at org.apache.commons.jcs.engine.control.CompositeCacheConfigurator.parseRegion(CompositeCacheConfigurator.java:319)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getCache(CompositeCacheManager.java:609)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getCache(CompositeCacheManager.java:549)
    at org.apache.commons.jcs.engine.control.CompositeCacheManager.getCache(CompositeCacheManager.java:536)
    at org.apache.commons.jcs.JCS.getGroupCacheInstance(JCS.java:194)
    at javastrava.cache.impl.StravaCacheImpl.<init>(StravaCacheImpl.java:40)
    at javastrava.api.v3.service.impl.ActivityServiceImpl.<init>(ActivityServiceImpl.java:93)
    at javastrava.api.v3.service.impl.ActivityServiceImpl.instance(ActivityServiceImpl.java:58)
    at javastrava.api.v3.auth.model.Token.<init>(Token.java:114)
    at Main.main(Main.java:33)

May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.memory.AbstractDoubleLinkedListMemoryCache initialize
INFO: initialized MemoryCache for default
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCache <init>
INFO: Constructed cache with name [default] and cache attributes [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 1000, maxSpoolPerRun = -1, diskUsagePattern = SWAP, spoolChunkSize = 2 ]
Exception in thread "main" java.lang.ExceptionInInitializerError
    at javastrava.api.v3.auth.model.Token.<init>(Token.java:123)
    at Main.main(Main.java:33)
Caused by: java.util.MissingResourceException: Can't find bundle for base name application, locale en_US
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
    at javastrava.api.v3.service.impl.WebhookServiceImpl.<clinit>(WebhookServiceImpl.java:28)
    ... 2 more
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCacheManager run
INFO: Shutdown hook activated.  Shutdown was not called.  Shutting down JCS.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.event.ElementEventQueue dispose
INFO: Element event queue destroyed: org.apache.commons.jcs.engine.control.event.ElementEventQueue@7c8c5901
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
INFO: In DISPOSE, [default] fromRemote [false]
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.control.CompositeCache dispose
INFO: In DISPOSE, [default] disposing of memory cache.
May 30, 2016 3:47:03 PM org.apache.commons.jcs.engine.memory.AbstractMemoryCache dispose
INFO: Memory Cache dispose called.
```

I thought the raw wasn't using any caching? Anything I did wrong?

**Comment by paulfournel** [comment]
👍 I get the same issue

**Comment by robinsm** [comment]
I also have the same issue, has any resolution been found?

**Comment by pnewhook** [comment]
The problem stems from [`WebHookServiceImpl` trying to load a missing resource file](https://github.com/danshannon/javastravav3api/blob/master/Strava%20API%20v3/src/javastrava/api/v3/service/impl/WebhookServiceImpl.java#L28). There's a properties file that needs to be added to the applicaiton, but isn't in README.md. You can find the sample application.properties at https://github.com/danshannon/javastravav3api/blob/50ebf3ccab333ef4e83ac2fb73425d947443e551/Strava%20API%20v3/src/sample-application.properties 

The offending code:

```
/**
 * Name of the configuration file
 */
private static final String BUNDLE_NAME = "application"; //$NON-NLS-1$

/**
 * Resource bundle containing configuration properties
 */
private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);
```

**Comment by danshannon** [comment]
Have raised an issue to deal with documenting the properties files properly. Closing this issue in favour of #144
