### ISSUE TITLE
test.api.rest.activity.ListFriendsActivitiesTest.testPageNumberAnd failure

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#168]
java.lang.AssertionError: 
expected:
```
StravaActivity [id=941169949, resourceState=2, externalId=4F4AA0FB-9CEE-453D-99AE-9E3228D2C045, athlete=StravaAthlete [id=8819681, resourceState=2, firstname=Ross, lastname=Barnard, profileMedium=https://dgalywyr863hv.cloudfront.net/pictures/athletes/8819681/3936290/2/medium.jpg, profile=https://dgalywyr863hv.cloudfront.net/pictures/athletes/8819681/3936290/2/large.jpg, city=Saint Lucia, state=QLD, country=Australia, sex=M, friend=accepted, follower=null, premium=true, createdAt=2015-04-22T08:04:55Z, updatedAt=2017-04-13T12:20:58Z, approveFollowers=null, followerCount=null, friendCount=null, mutualFriendCount=null, datePreference=null, meaurementPreference=null, email=null, ftp=null, clubs=null, bikes=null, shoes=null, weight=null, badgeTypeId=1, athleteType=null, username=null], name=Morning Ride, description=null, distance=108828.0, movingTime=17330, elapsedTime=20941, totalElevationGain=347.1, type=ride, startDate=2017-04-13T21:25:08Z, startDateLocal=2017-04-14T07:25:08, timezone=(GMT+10:00) Australia/Brisbane, startLatlng=StravaMapPoint [latitude=-27.48, longitude=152.98], endLatlng=StravaMapPoint [latitude=-27.48, longitude=152.98], locationCity=Toowong, locationState=Queensland, locationCountry=Australia, achievementCount=9, kudosCount=0, commentCount=0, athleteCount=1, photoCount=0, totalPhotoCount=0, map=StravaMap [id=a941169949, polyline=null, summaryPolyline=dfvfDqkvd\yHy@HeObJiNxGen@qmAa|AsIqd@jPm]bt@sm@bTvR_B}f@k_@uPmbA~@~a@iJ}{@~@t[g_@hv@mLcAc[e^gg@eK}Aud@zWui@Pqe@xZaa@yA_AbLaSuJOqaB{JkCiKsp@fVJvLae@}^_XtOlLrAkr@mUyDR}`@fLeMkn@sjBav@qr@s^}Rh\`xB_CdRgGeGtA_KdHBmGxw@qh@nv@~IvTuSyFnAbRy^bg@zA|GyJd@jIjClFnZuMyXrDkAxIlX_OuTfDoBjIvZaP{e@yE}|@kVeUmh@bBuEef@s|@{]sa@sk@eT|DcXr[maCy]wO@yJxYeKl@pWu[vNS|cCn]dV_[rT{Dz_@`j@f}@z_@hFlf@tg@iBxVxTxEl}@rTfc@aVu\pJSsB{Gh_@mf@iA{RhSrFmGiQzDaSt_@q_@hC_^}^sa@tc@wBi[yqBj]bRp`ApeAhf@z{AgEfFzDmD{DvCxCyF{M{i@o\rDtGbh@hmAak@ulAlq@eJop@~^yDjN`m@qL|JKp`@nTfFuIjzAbMfBtBnMsJp\~BnoBtSvKd@oLpi@RhTcTdw@wDfa@}Vhf@jc@bGnWaDzLqs@pIe\z^v{@WqNtGvp@i@l^xQbBvf@iT{Rwt@`m@yOl\pI|e@tnAp|A_Irm@_JzLQhP|Hp@, resourceState=2], trainer=false, commute=false, manual=false, privateActivity=false, flagged=false, workoutType=10, gearId=b2056694, gear=null, averageSpeed=6.28, maxSpeed=14.7, averageCadence=null, averageTemp=null, averageWatts=118.3, weightedAverageWatts=null, kilojoules=2050.5, deviceWatts=false, hasHeartrate=false, averageHeartrate=null, maxHeartrate=null, calories=null, hasKudoed=false, segmentEfforts=null, splitsMetric=null, splitsStandard=null, bestEfforts=null, uploadId=1041513228, startLatitude=-27.48, startLongitude=152.98, instagramPrimaryPhoto=null, photos=null, video=null, embedToken=null, deviceName=null, sufferScore=null, utcOffset=36000.0, elevHigh=92.0, elevLow=-6.1, prCount=3, maxWatts=null, laps=null, similarActivities=null]
```
but was:
```
StravaActivity [id=941170091, resourceState=2, externalId=D7BC44E8-F446-41DC-939E-ADE979B0E132, athlete=StravaAthlete [id=146494, resourceState=2, firstname=Lou, lastname=Cannata, profileMedium=https://dgalywyr863hv.cloudfront.net/pictures/athletes/146494/21476/2/medium.jpg, profile=https://dgalywyr863hv.cloudfront.net/pictures/athletes/146494/21476/2/large.jpg, city=Glen Iris, state=VIC, country=Australia, sex=M, friend=accepted, follower=null, premium=false, createdAt=2011-09-20T14:18:56Z, updatedAt=2016-12-04T21:48:43Z, approveFollowers=null, followerCount=null, friendCount=null, mutualFriendCount=null, datePreference=null, measurementPreference=null, email=null, ftp=null, clubs=null, bikes=null, shoes=null, weight=null, badgeTypeId=0, athleteType=null, username=lcannata], name=Good Friday, Great Crew, description=null, distance=103176.0, movingTime=17860, elapsedTime=21657, totalElevationGain=1461.9, type=ride, startDate=2017-04-13T21:14:05Z, startDateLocal=2017-04-14T07:14:05, timezone=(GMT+10:00) Australia/Melbourne, startLatlng=StravaMapPoint [latitude=-37.85, longitude=145.08], endLatlng=StravaMapPoint [latitude=-37.85, longitude=145.08], locationCity=Glen Iris, locationState=VIC, locationCountry=Australia, achievementCount=52, kudosCount=1, commentCount=0, athleteCount=1, photoCount=0, totalPhotoCount=0, map=StravaMap [id=a941170091, polyline=null, summaryPolyline=vv~eF}pmtZyvArbBsRdD|T}jEyVmD|Boj@}vCk\{CfYkvAyO_Ma~@hBo}@}I_oBvXm}EyA{Jm`@qd@oi@mWag@ewAge@fC}IyUy_@wSes@iW_n@aF_a@kz@K_LuL_Bmh@_q@mr@|f@oYuFeUlX}UsGsV_Z{NvAkb@b]{Efn@c|@mMsMcTguAoMwmAwe@y^w^~Wg^yA_ZnTeq@|gAod@oa@cc@}Jcl@uViDaYm_@wF__@_Ss]eg@hI}StWcRpFeQ^gIuYqVtM_DzGhBlUqIv\wa@lYqJdVdBvC{aBuZzzAnTbf@zz@pk@l`@fNpXtNhB~GdQrOxFpArF{VbUwb@nJ}EtIyArZvHf`AuEht@hWrk@vU}Ubp@}TpN`C`k@si@|r@wAfg@iUhC_YjfApNbMxStxAxOfMxKkJvfBj`AtR_BvVaQfMwKda@yJnIwH|g@xDh{@`HjY{BlWtSrZn{Aj[da@sErQhKxPlc@pUkChGr]p^wKpiA|LgAxVpLtAc@~fAty@wDdn@``@tb@pGxv@lr@pf@l{BbtDpb@oGtsA~tAxSnz@ebA, resourceState=2], trainer=false, commute=false, manual=false, privateActivity=false, flagged=false, workoutType=10, gearId=null, gear=null, averageSpeed=5.777, maxSpeed=18.8, averageCadence=null, averageTemp=null, averageWatts=135.2, weightedAverageWatts=null, kilojoules=2414.5, deviceWatts=false, hasHeartrate=false, averageHeartrate=null, maxHeartrate=null, calories=null, hasKudoed=false, segmentEfforts=null, splitsMetric=null, splitsStandard=null, bestEfforts=null, uploadId=1041513430, startLatitude=-37.85, startLongitude=145.08, instagramPrimaryPhoto=null, photos=null, video=null, embedToken=null, deviceName=null, sufferScore=null, utcOffset=36000.0, elevHigh=246.2, elevLow=23.1, prCount=12, maxWatts=null, laps=null, similarActivities=null]
```
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at test.api.rest.APIPagingListTest.lambda$0(APIPagingListTest.java:76)
	at test.utils.RateLimitedTestRunner.run(RateLimitedTestRunner.java:35)
	at test.api.rest.APIPagingListTest.testPageNumberAndSize(APIPagingListTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by danshannon** [comment]
Caused by someone posting an activity while test was running. Working as expected now.
