### ISSUE TITLE
Failed to read configuration file [/cache.ccf]

### ISSUE THREAD

**Issue by devrajatverma** [danshannon/javastravav3api#188]
**cache.ccf** file at the root of the project directory
contains following:
```
# DEFAULT CACHE REGION

jcs.default=
jcs.default.cacheattributes=org.apache.commons.jcs.engine.CompositeCacheAttributes
jcs.default.cacheattributes.MaxObjects=200001
jcs.default.cacheattributes.MemoryCacheName=org.apache.commons.jcs.engine.memory.lru.LRUMemoryCache
jcs.default.cacheattributes.UseMemoryShrinker=true
jcs.default.cacheattributes.MaxMemoryIdleTime=3600
jcs.default.cacheattributes.ShrinkerInterval=60
jcs.default.elementattributes=org.apache.commons.jcs.engine.ElementAttributes
jcs.default.elementattributes.IsEternal=false
jcs.default.elementattributes.MaxLife=3600
jcs.default.elementattributes.IsSpool=false
jcs.default.elementattributes.IsRemote=false
jcs.default.elementattributes.IsLateral=false
```

**StackTrace:**

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: org.apache.commons.jcs.access.exception.CacheException: Failed to read configuration file [/cache.ccf]]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: java.util.concurrent.CompletionException: org.apache.commons.jcs.access.exception.CacheException: Failed to read configuration file [/cache.ccf]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
Caused by: org.apache.commons.jcs.access.exception.CacheException: Failed to read configuration file [/cache.ccf]
	at org.apache.commons.jcs.engine.control.CompositeCacheManager.configure(CompositeCacheManager.java:359)
	at org.apache.commons.jcs.engine.control.CompositeCacheManager.getInstance(CompositeCacheManager.java:190)
	at org.apache.commons.jcs.engine.control.CompositeCacheManager.getInstance(CompositeCacheManager.java:161)
	at org.apache.commons.jcs.JCS.getCacheManager(JCS.java:156)
	at org.apache.commons.jcs.JCS.getGroupCacheInstance(JCS.java:219)
	at javastrava.cache.impl.StravaCacheImpl.<init>(StravaCacheImpl.java:40)
	at javastrava.api.v3.service.impl.ActivityServiceImpl.<init>(ActivityServiceImpl.java:93)
	at javastrava.api.v3.service.impl.ActivityServiceImpl.instance(ActivityServiceImpl.java:58)
	at javastrava.api.v3.auth.model.Token.<init>(Token.java:114)
	at javastrava.api.v3.auth.impl.retrofit.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:40)

```

**Comment by devrajatverma** [comment]
https://stackoverflow.com/questions/53299235/cache-ccf-file-not-picked-up-by-javastravav3api

**Comment by devrajatverma** [comment]
after putting it into conf folder the above issue is resolved but after that another did pop up

```
[warn] o.a.c.j.u.c.PropertySetter - No such property [maxMemoryIdleTime] in org.apache.commons.jcs.engine.CompositeCacheAttributes.
[warn] o.a.c.j.u.c.PropertySetter - No such property [shrinkerInterval] in org.apache.commons.jcs.engine.CompositeCacheAttributes.
[error] a.a.ActorSystemImpl - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-8] shutting down ActorSystem [application]
java.lang.ExceptionInInitializerError: null
	at javastrava.api.v3.auth.model.Token.<init>(Token.java:123)
	at javastrava.api.v3.auth.impl.retrofit.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:40)
	at controllers.StravaController.doOauthDanceForCode(StravaController.java:25)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:353)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:353)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
	at play.http.HttpRequestHandler$1.call(HttpRequestHandler.java:54)
Caused by: java.util.MissingResourceException: Can't find bundle for base name application, locale en_IN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
	at javastrava.api.v3.service.impl.WebhookServiceImpl.<clinit>(WebhookServiceImpl.java:28)
	at javastrava.api.v3.auth.model.Token.<init>(Token.java:123)
	at javastrava.api.v3.auth.impl.retrofit.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:40)
	at controllers.StravaController.doOauthDanceForCode(StravaController.java:25)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:353)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:353)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)

```

**Comment by devrajatverma** [comment]
Fix:
in cache.ccf

jcs.default.cacheattributes.MaxMemoryIdleTimeSeconds=3600
jcs.default.cacheattributes.ShrinkerIntervalSeconds=60

**Comment by devrajatverma** [comment]
after fixing this i got this
```
[error] a.a.ActorSystemImpl - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-2] shutting down ActorSystem [application]
java.lang.ExceptionInInitializerError: null
	at javastrava.api.v3.auth.model.Token.<init>(Token.java:123)
	at javastrava.api.v3.auth.impl.retrofit.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:40)
	at controllers.StravaController.doOauthDanceForCode(StravaController.java:25)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:353)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:353)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
	at play.http.HttpRequestHandler$1.call(HttpRequestHandler.java:54)
Caused by: java.util.MissingResourceException: Can't find bundle for base name application, locale en_IN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
	at javastrava.api.v3.service.impl.WebhookServiceImpl.<clinit>(WebhookServiceImpl.java:28)
	at javastrava.api.v3.auth.model.Token.<init>(Token.java:123)
	at javastrava.api.v3.auth.impl.retrofit.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:40)
	at controllers.StravaController.doOauthDanceForCode(StravaController.java:25)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:353)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:353)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)

```
