### ISSUE TITLE
Cannot store a token if the athlete has no email

### ISSUE THREAD

**Issue by vandeseer** [danshannon/javastravav3api#194]
Due to a recent change in the API one gets this error on token exchange: 

    Exception in thread "main" java.lang.IllegalArgumentException: Cannot store a token if the athlete has no email
    	at javastrava.auth.TokenManager.storeToken(TokenManager.java:220)
    	at javastrava.auth.impl.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:41)

There is a fix for it (plus a bit more details) in this pull request: https://github.com/danshannon/javastravav3api/pull/193

**Comment by semteXKG** [comment]
is there any chance we can get this merged to master / released somewhere in the future? Can I help somehow? I just wanna know where i'm at (and if I should wait a little longer or just fork the thing).
