### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#35]
`HTTP GET https://www.strava.com/api/v3/segments/966356/all_efforts?start_date_local=2015-01-01T18%3A10%3A47%2B11&end_date_local=9999-12-31T18%3A11%3A07%2B11&page=9&per_page=200`

throws a 500 Internal Server Error

**Comment by danshannon** [comment]
Stack trace:
```
javastrava.api.v3.service.exception.StravaUnknownAPIException: 500 Internal Server Error : StravaResponse(message=error, errors=null)
	at javastrava.api.v3.service.impl.retrofit.RetrofitErrorHandler.handleError(RetrofitErrorHandler.java:89)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
	at com.sun.proxy.$Proxy23.listSegmentEfforts(Unknown Source)
	at javastrava.api.v3.service.impl.retrofit.SegmentServicesImpl$3.getPageOfData(SegmentServicesImpl.java:188)
	at javastrava.api.v3.service.PagingHandler.handlePaging(PagingHandler.java:46)
	at javastrava.api.v3.service.impl.retrofit.SegmentServicesImpl.listSegmentEfforts(SegmentServicesImpl.java:185)
	at javastrava.api.v3.service.impl.retrofit.SegmentServicesImpl$7.getPageOfData(SegmentServicesImpl.java:505)
	at javastrava.api.v3.service.PagingHandler.handleListAll(PagingHandler.java:88)
	at javastrava.api.v3.service.impl.retrofit.SegmentServicesImpl.listAllSegmentEfforts(SegmentServicesImpl.java:501)
	at test.api.service.impl.retrofit.segmentservices.ListAllSegmentEffortsTest.listAllSegmentEfforts_filterByAfterDate(ListAllSegmentEffortsTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: retrofit.RetrofitError: 500 Internal Server Error
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	... 31 more

```

**Comment by danshannon** [comment]
Also happening with
`HTTP GET https://www.strava.com/api/v3/segments/966356/all_efforts?page=50&per_page=200`

**Comment by paulmach** [comment]
I fixed this particular segment, but there are others.

**Comment by danshannon** [comment]
Closed, fixed

**Comment by danshannon** [comment]
Thanks Paul!
