### ISSUE TITLE
Invalid authorisation code causes 500 internal server error

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#56]
`GET https://www.strava.com/oauth/authorize?client_id=511&response_type=code&redirect_uri=http%3A%2F%2Flocalhost&approval_prompt=force&scope=UNKNOWN%2C` causes Strava to return a `500 Internal Server Error`

See stack trace in comments below

**Comment by danshannon** [comment]
```
javastrava.api.v3.service.exception.StravaInternalServerErrorException: GET https://www.strava.com/oauth/authorize?client_id=511&response_type=code&redirect_uri=http%3A%2F%2Flocalhost&approval_prompt=force&scope=UNKNOWN%2C returned status 500 : null
	at test.utils.TestHttpUtils.httpGet(TestHttpUtils.java:62)
	at test.utils.TestHttpUtils.getAuthorisationPageAuthenticityToken(TestHttpUtils.java:211)
	at test.utils.TestHttpUtils.approveApplication(TestHttpUtils.java:255)
	at test.utils.TestHttpUtils.getStravaAccessToken(TestHttpUtils.java:284)
	at test.api.auth.impl.retrofit.AuthorisationServiceImplTest$8.test(AuthorisationServiceImplTest.java:293)
	at test.utils.RateLimitedTestRunner.run(RateLimitedTestRunner.java:29)
	at test.api.auth.impl.retrofit.AuthorisationServiceImplTest.testTokenExchange_invalidScope(AuthorisationServiceImplTest.java:289)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by danshannon** [comment]
Needs an issue test
